### ISSUE TITLE
FindBoost BoostVersion and cmake version

### ISSUE THREAD

**Issue by JensWehner** [votca/buildenv#16]
Higher versions of boost require higher versions of cmake, then our minimum requirement. 

Boost 1.63 requires CMake 3.7 or newer.
Boost 1.64 requires CMake 3.8 or newer.
Boost 1.65 and 1.65.1 require CMake 3.9.3 or newer.
Boost 1.66 requires CMake 3.11 or newer.
Boost 1.67 is only supported by CMake

https://stackoverflow.com/questions/42123509/cmake-finds-boost-but-the-imported-targets-not-available-for-boost-version

I got the crash which was described here.

**Comment by JensWehner** [comment]
maybe it is not a large issue, it happened here because the update from 16.04 to 18.04 is not as seamless as it should be.

**Comment by junghans** [comment]
Huh, what is the issue? 

I cannot reproduce this in Ubuntu-18.04 docker container:
```bash
docker run -it ubuntu:18.04 /bin/bash
```
then
```bash
apt-get -q update -y
apt-get install -y make cmake git g++ libexpat-dev libfftw3-dev libgsl-dev libboost-all-dev txt2tags libsqlite3-dev ccache octave gnuplot python-numpy ghostscript texlive doxygen vim clang llvm python-pip python-lxml inkscape transfig wget libhdf5-dev graphviz pkg-config texlive-latex-extra psmisc texlive-pstricks libint2-dev libeigen3-dev libxc-dev libceres-dev
apt-get install -y libgromacs-dev gromacs-openmpi
git clone --recursive https://github.com/votca/votca
cd votca/
mkdir build
cd build/
cmake ../ -DBUILD_CTP=ON -DBUILD_CSGAPPS=ON -DBUILD_XTP=ON -DBUILD_CTP_MANUAL=ON -DBUILD_XTP_MANUAL=ON -DBUILD_CSG_MANUAL=ON
make -j5
 ```
gives success!

**Comment by baumeier** [comment]
Where did that happen? AFAIK, 18.04 comes with boost 1.65.x and CMake 3.10.y. 
If it was on one of our machines, we had a manual install of CMake 3.9 in 16.04. Boost gets updated by the 18.04 update, but for CMake one has to replace the self-installed one by the repo version.

**Comment by JensWehner** [comment]
yeah, that is exaclty what happened. Question is if we should detect that or not? It happened on ICMS74

**Comment by junghans** [comment]
I don't think we should add random checks to protect us against screwed up systems!
